# Generated by Django 6.0.3 on 2026-03-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, verbose_name='Renavam')),
                ('service_type', models.CharField(choices=[('Transferência', 'Transferência'), ('Licenciamento', 'Licenciamento'), ('Emplacamento', 'Emplacamento'), ('Segunda via', 'Segunda via'), ('Multa', 'Multa'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Serviço')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Aguardando cliente', 'Aguardando cliente'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=50, verbose_name='Status')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('opened_at', models.DateField(verbose_name='Data de Abertura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('payment_status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=50, verbose_name='Status de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.client', verbose_name='Cliente')),
            ],
        ),
    ]
