# Generated by Django 6.0.3 on 2026-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='value',
        ),
        migrations.AddField(
            model_name='process',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='process',
            name='service_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Serviço'),
        ),
        migrations.AddField(
            model_name='process',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor das Taxas'),
        ),
    ]
