# Generated by Django 6.0.3 on 2026-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_process_value_process_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor das Taxas'),
        ),
    ]
